# Generated by Django 3.2.4 on 2021-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(default=''),
        ),
    ]
